name: test_deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"

      - name: setup project
        run: npm install -g yarn && yarn install

      - name: build
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: dev.ceshmina.jp
          publish_branch: test_release
